### PR TITLE
refactor[ia]:changing project to mvc

### PR DESCRIPTION
**Pull request by Stefan-Kitanovic**
Initially our project was created from a Razor pages template, but we found out that it wouldn't work well with REST controllers, so I have changed entire project to classic ASP.NET MVC instead.

### CODE REVIEW

**Review by borislav-puzic — DISMISSED** [review]
lgtm

**Review by milana-todorovic — CHANGES_REQUESTED** [review]
When creating the project, did you uncheck the 'Configure for HTTPS option'? It keeps asking me to install a security certificate when I try to run the project, I think that was supposed to be turned off like the instructions [here](https://www.youtube.com/watch?v=xK0oyVIA7o4&feature=youtu.be&ab_channel=pswftn) say.

**Comment by Stefan-Kitanovic** [comment]
I left it checked while I was creating the project by accident,  I think it should be disabled now.

**Review by borislav-puzic — APPROVED** [review]
All good, run project this time and https is off

**Review by milana-todorovic — APPROVED** [review]
Seems alright now, I don't have any issues with running the project.

**Pull request merged**
