### PR TITLE
feat[w2.6]: start creating a survey form

### PR DESCRIPTION
**Pull request by jelenazeljko55**
I have a goal to design html page for survey.

### CODE REVIEW

**Comment by jelenazeljko55** [comment]
[(5) W2.6 As a patient I want to fill out the survey about the hospital so that I could share my experience.](https://trello.com/c/MvcNCcZS/25-5-w26-as-a-patient-i-want-to-fill-out-the-survey-about-the-hospital-so-that-i-could-share-my-experience)

**Review by anciz — COMMENTED** [review]
You should request a review from your members of team(or from other teams). Please, try to do it or if you disagree, let us know and we will discuss about it to find better solution.

**Review by anciz — DISMISSED** [review]
Alright!

**Review by milana-todorovic — DISMISSED** [review]
Seems alright.

**Review by vlaksi — APPROVED** [review]
Lgtm

**Review by milana-todorovic — APPROVED** [review]
Seems alright, but you might have issues with the fact that the buttons have the same ids when you try to fetch them from jQuery. I don't mind if you leave it as is and change it later when you actually need it though.

**Pull request merged**
