### PR TITLE
gui[g-all]: GUI Panels Redesign, Switched to Grids, Added Styles and Transitions

### PR DESCRIPTION
**Pull request by VasilijeBursac**
This branch contains mostly XAML code for different application functionalities.
I left few unimplemented methods in MainWindow.cs, but that will be replaced with implemented methods in next commits. I did that just to avoid deleting event handler declarations from xaml code. 

- I have moved DataGrid Styles to App.xaml
- I needed to copy  to App.xaml files of other WPF applications so that Application doesn't break, but in future I plan to make other WPF Apps use GraphicalEditor App.xaml without repeating code for GraphicalEditor Styles
- Most of MainWindow.xaml is switched to using Grids because of previous problems with DataGrids that StackPanels caused
- Transitions Animations for Canvas load and menu options switching

Small redesign of: 
- Panels for selected object's equipment and medicine overview
- Panel for searching map objects
- Panel for searching equipment and medicine
- Panel for searching map objects

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g2.1: Search for objects on the map: 4h [2]](https://trello.com/c/zdABDaG8/34-2-g21-search-for-objects-on-the-map-4h-2)

**Comment by VasilijeBursac** [comment]
[(1) g2.2: Advanced search for objects on the map: 5h [3]](https://trello.com/c/rpdorYqc/35-1-g22-advanced-search-for-objects-on-the-map-5h-3)

**Comment by VasilijeBursac** [comment]
[(1) g2.2: Advanced search for objects on the map: 5h [3]](https://trello.com/c/rpdorYqc/35-1-g22-advanced-search-for-objects-on-the-map-5h-3)

**Comment by VasilijeBursac** [comment]
[(3) g2.3: Overview of equipment and medicine: 5h[3]](https://trello.com/c/AQBpJl1G/36-3-g23-overview-of-equipment-and-medicine-5h3)

**Comment by VasilijeBursac** [comment]
[(2) g2.4: Search for equipment and medicine: 2.5h [2]](https://trello.com/c/o48wFYVz/37-2-g24-search-for-equipment-and-medicine-25h-2)

**Comment by VasilijeBursac** [comment]
[(1) g2.5: Advanced search for equipment and medicine: 1h [1]](https://trello.com/c/v3kGqtRO/38-1-g25-advanced-search-for-equipment-and-medicine-1h-1)

**Review by Pufke — APPROVED** [review]

**Review by vlaksi — APPROVED** [review]
Seems fine.

**Pull request merged**
