### PR TITLE
fix[g8]: improved mouse click code to prevent bugs with changing floors

### PR DESCRIPTION
**Pull request by VasilijeBursac**
Code from this branch handles mouse click on map objects and hover over them. 
All of the code from this branch was already approved. 
**I just added additional  condition to prevent bug that was happening on mouse click after building floor is switched.**

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g8: Display all information (description, working hours,...): 6h [3]](https://trello.com/c/4uXEv66o/8-2-g8-display-all-information-description-working-hours-6h-3)

**Review by vlaksi — APPROVED** [review]
Great fix, great pull request description @VasilijeBursac . Only one suggestion, on the next pull request, require a code review from one(min) member of your team.

**Comment by VasilijeBursac** [comment]
> Great fix, great pull request description @VasilijeBursac . Only one suggestion, on the next pull request, require a code review from one(min) member of your team.

@vlaksi Thank you! Okay, I will do it on the next pull request.

**Review by milana-todorovic — APPROVED** [review]
Seems alright.

**Pull request merged**
