### PR TITLE
feat[g2.1]: Search for objects on the map

### PR DESCRIPTION
**Pull request by VasilijeBursac**
This branch contains code for searching map objects. 

- Using static attribute _allMapObjects from MainWindow definitely isn't the best option but this will be fixed and a special class will be created at the end of this sprint probably or maybe during next week.

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g2.1: Search for objects on the map: 4h [2]](https://trello.com/c/zdABDaG8/34-2-g21-search-for-objects-on-the-map-4h-2)

**Review by milana-todorovic — APPROVED** [review]
I definitely agree with you about using the static field not being a good idea, but since you'll be refactoring anyway I think this is okay enough for now. One thing I'd just say is that maybe things would've been easier for you if you'd just left the SearchMapObjects method logic in the MainWindow for now anyway since the field it needs is there, it might be a little harder to untangle this when refactoring now.

**Comment by VasilijeBursac** [comment]
> I definitely agree with you about using the static field not being a good idea, but since you'll be refactoring anyway I think this is okay enough for now. One thing I'd just say is that maybe things would've been easier for you if you'd just left the SearchMapObjects method logic in the MainWindow for now anyway since the field it needs is there, it might be a little harder to untangle this when refactoring now.

Thanks for the advice! I agree, but it would increase the amount of code in MainWindow so it is easier for us to leave it like this for now...

**Review by kmilena98 — APPROVED** [review]
Looks good to me.

**Pull request merged**
