### PR TITLE
fix: detach WPF frontends from the Backend project to remove issues with refactoring

### PR DESCRIPTION
**Pull request by milana-todorovic**
In the SIMS legacy code, the Backend was a class library that the WPF frontends reference directly, which made them tightly coupled and impeded current development and refactoring on the Backend. To fix this issue, the LegacyBackend project, which contains the final version of Backend from SIMS before refactoring, was added to the solution, and the references in the SecretaryFrontend, ManagerFrontend, and DoctorFrontend were switched from Backend to LegacyBackend. Changes in the WPF projects caused by Backend refactoring were also reverted to comply with the legacy version, while changes made because of GraphicalEditor requirements were kept. 
This is a temporary patch meant to make development easier. The plan is to implement communication between the Backend and the WPF frontends via HTTP or some other protocol step by step. Once this is completed LegacyBackend will be deleted.

Since it seemed related to these changes, the legacy PatientFrontend from SIMS was also added on this branch because it's needed for the GraphicalEditor. The PatientFrontend doesn't reference LegacyBackend because it was never connected to the Backend in the legacy code - it contains copies of the needed classes from the old Backend instead. This will eventually be deleted similarly to LegacyBackend.

### CODE REVIEW

**Comment by milana-todorovic** [comment]
Review was requested from members of the GraphicalEditor team (specifically for the commit 8e3b2f2e31e875422baf7b620728cb7a3d809e22 ) to make sure that none of the changes made to the WPF frontends made because of GraphicalEditor requirements were harmed while reverting the changes caused by Backend refactoring.

**Comment by VasilijeBursac** [comment]
> Review was requested from members of the GraphicalEditor team (specifically for the commit [8e3b2f2](https://github.com/PSW-2020-ORG4/HealthcareSystem/commit/8e3b2f2e31e875422baf7b620728cb7a3d809e22) ) to make sure that none of the changes made to the WPF frontends made because of GraphicalEditor requirements were harmed while reverting the changes caused by Backend refactoring.

Links to GraphicalEditor project from WPFs seem to be fine. 

This WPFs now probably have older version of MaterialDesign in them, and Doctor Frontend doesn't have it, but that is okay, I will add it manually and make separate PR for that. 
(Explanation: MaterialDesign version in Manager and Secretary WPFs needs to be updated to latest version (this was necessary because versions in GraphicalEditor and other WPFs need to match because these WPFs call GraphicalEditor. MaterialDesign also needs to be installed in Doctor Frontend because it calls GraphicalEditor project). 
I will add all of those in next PR, so just ignore that. 

**Generally, everything seems to be okay.**

**Review by kmilena98 — DISMISSED** [review]
Looks good to me

**Comment by milana-todorovic** [comment]
> > Review was requested from members of the GraphicalEditor team (specifically for the commit [8e3b2f2](https://github.com/PSW-2020-ORG4/HealthcareSystem/commit/8e3b2f2e31e875422baf7b620728cb7a3d809e22) ) to make sure that none of the changes made to the WPF frontends made because of GraphicalEditor requirements were harmed while reverting the changes caused by Backend refactoring.
> 
> Links to GraphicalEditor project from WPFs seem to be fine. I can't see WPF for patient. We need to connect it to GraphicalEditor, too.
> 
> This WPFs now probably have older version of MaterialDesign in them, and Doctor Frontend doesn't have it, but that is okay, I will add it manually and make separate PR for that.
> (Explanation: MaterialDesign version in Manager and Secretary WPFs needs to be updated to latest version (this was necessary because versions in GraphicalEditor and other WPFs need to match because these WPFs call GraphicalEditor. MaterialDesign also needs to be installed in Doctor Frontend because it calls GraphicalEditor project).
> I will add all of those in next PR, so just ignore that.
> 
> **Generally, everything seems to be okay, just add Patient Frontend to solution if you haven't done that yet.**

I actually think they do have the correct version of MaterialDesign (except for the PatientFrontend), I kept changes from the branch where you changes the packages when I merged it.

**Comment by VasilijeBursac** [comment]
> > > Review was requested from members of the GraphicalEditor team (specifically for the commit [8e3b2f2](https://github.com/PSW-2020-ORG4/HealthcareSystem/commit/8e3b2f2e31e875422baf7b620728cb7a3d809e22) ) to make sure that none of the changes made to the WPF frontends made because of GraphicalEditor requirements were harmed while reverting the changes caused by Backend refactoring.
> > 
> > 
> > Links to GraphicalEditor project from WPFs seem to be fine. I can't see WPF for patient. We need to connect it to GraphicalEditor, too.
> > This WPFs now probably have older version of MaterialDesign in them, and Doctor Frontend doesn't have it, but that is okay, I will add it manually and make separate PR for that.
> > (Explanation: MaterialDesign version in Manager and Secretary WPFs needs to be updated to latest version (this was necessary because versions in GraphicalEditor and other WPFs need to match because these WPFs call GraphicalEditor. MaterialDesign also needs to be installed in Doctor Frontend because it calls GraphicalEditor project).
> > I will add all of those in next PR, so just ignore that.
> > **Generally, everything seems to be okay, just add Patient Frontend to solution if you haven't done that yet.**
> 
> I actually think they do have the correct version of MaterialDesign (except for the PatientFrontend), I kept changes from the branch where you changes the packages when I merged it.

Great! 😄👏 I will test that after PR is merged.

**Review by VasilijeBursac — APPROVED** [review]

**Comment by VasilijeBursac** [comment]
Everything seems to be okay.

**Review by vlaksi — APPROVED** [review]
Lgtm.

**Pull request merged**
