### PR TITLE
Chore[d54]: Solution reorganized to enable CI implementation

### PR DESCRIPTION
**Pull request by milana-todorovic**
- References from GraphicalEditorServer to GraphicalEditor and from GraphicalEditor to Backend were removed. Backend and GraphicalEditorServer form the server, while GraphicalEditor is their client, and they should not share classes. The references existed because some of the DTOs exchanged in HTTP communication were located in GraphicalEditor and some in Backend. The necessary DTOs are now copied into all projects that participate in the client-server interaction.
- GraphicalEditor, ManagerFrontend, SecretaryFrontend, PatientFrontend, DoctorFrontend, and LegacyBackend were moved into a separate solution to avoid cluttering and simplify the CI build process.

@PSW-2020-ORG4/devops Check if build works.
@VasilijeBursac @ogikuzma @kmilena98 @djura023 I would also appreciate if one of you checked if everything is okay, since parts of your project were moved and modified.

### CODE REVIEW

**Review by vlaksi — DISMISSED** [review]
### Check

  - [x] HealthcareSystem work image
  - [x] HealthcareSystemFrontends image

### Comment

All check is okay and seems fine to me.

**Review by milana-todorovic — COMMENTED** [review]
Everything seem fine to me after the migration, I'm not getting any build issues.

**Comment by Pufke** [comment]
Not Bad, Not Terrible❤️❤️❤️

**Review by Pufke — APPROVED** [review]

**Review by anciz — APPROVED** [review]
Build is right.

**Review by ogikuzma — APPROVED** [review]
Build works. Connection with database works.

**Comment by milana-todorovic** [comment]
[(1) Move pipeline configurations from test project to real project [d54] [1] - 2h](https://trello.com/c/nxBN8fBV/54-1-move-pipeline-configurations-from-test-project-to-real-project-d54-1-2h)

**Pull request merged**
