### PR TITLE
gui[g-general]: Implemented menu, GUI Panels for searches, object equipment and medicine overview

### PR DESCRIPTION
**Pull request by VasilijeBursac**
This branch contains mostly XAML code for menu options and different application functionalities.

- Switching menu options and panels depending on selected menu option
- Panels for selected object's equipment and medicine overview
- Panel for searching map objects
- Panel for searching equipment and medicine
- Panel for searching terms
- Panel for searching map objects

Data grids and some of the other controls don't have any binding yet, but we will bind them during further implementation.
This is just to make general switching logic and layout so we can implement these functionalities.

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g2.1: Search for objects on the map](https://trello.com/c/zdABDaG8/34-2-g21-search-for-objects-on-the-map)

**Comment by VasilijeBursac** [comment]
[(3) g2.3: Overview of equipment and medicine](https://trello.com/c/AQBpJl1G/36-3-g23-overview-of-equipment-and-medicine)

**Comment by VasilijeBursac** [comment]
[(2) g2.4: Search for equipment and medicine](https://trello.com/c/o48wFYVz/37-2-g24-search-for-equipment-and-medicine)

**Comment by VasilijeBursac** [comment]
[(3) g2.6: Search for available term](https://trello.com/c/4ywjCjIH/39-3-g26-search-for-available-term)

**Review by milana-todorovic — APPROVED** [review]
Looks really nice! Though I do suggest extracting the different sidebars into components at some point, either with MVVM or just regular components with exposed properties you can bind to. Mostly just to cut down on the amount of code in MainWindow.xaml, it's probably getting pretty hard to work with at this point.

**Review by anciz — APPROVED** [review]
Alright.

**Comment by VasilijeBursac** [comment]
> Looks really nice! Though I do suggest extracting the different sidebars into components at some point, either with MVVM or just regular components with exposed properties you can bind to. Mostly just to cut down on the amount of code in MainWindow.xaml, it's probably getting pretty hard to work with at this point.

Thanks!
I plan to do that, but since I don't have any experience with MVVM and I am not sure how it will work with passing data form UserControls and MainWindow, I left it like this.
But I definitely agree with you about that and at some suitable point in time I will change that.

**Comment by VasilijeBursac** [comment]
[(1) g2.2: Advanced search for objects on the map: 5h [3]](https://trello.com/c/rpdorYqc/35-1-g22-advanced-search-for-objects-on-the-map-5h-3)

**Comment by VasilijeBursac** [comment]
[(1) g2.5: Advanced search for equipment and medicine: 1h [1]](https://trello.com/c/v3kGqtRO/38-1-g25-advanced-search-for-equipment-and-medicine-1h-1)

**Pull request merged**
