### PR TITLE
chore[ia0]:setup initial integration adapters project

### PR DESCRIPTION
**Pull request by borislav-puzic**
I have setup initial project, and made starting classes for my team.

### CODE REVIEW

**Review by milana-todorovic — COMMENTED** [review]
Merge develop with this branch to resolve conflicts before review.

**Review by milana-todorovic — DISMISSED** [review]
Seems alright to me.

**Review by Stefan-Kitanovic — APPROVED** [review]
Everything looks good right now

**Review by milana-todorovic — APPROVED** [review]
Seems alright. Quick note, we usually mark conflict resolving with merge instead of chore.

**Pull request merged**
