### PR TITLE
gui[g4.4]: Entry data for Equipment Relocation, Scheduling Equipment Relocation and Alternative Appointments for Equipment Relocation Dialog

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains mostly frontend XAML code for "Data entry for equipment relocation", "Alternative appointments for equipment relocation" and "Scheduling equipment relocation".
- It contains dialog for equipment relocation and connection with equipment in object table

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g4.4: Entry data for equipment relocation](https://trello.com/c/VLZmjyrm/55-2-g44-entry-data-for-equipment-relocation)

**Comment by VasilijeBursac** [comment]
[(5) g4.6: Alternative appointments for equipment relocation](https://trello.com/c/XUKYT4eX/57-5-g46-alternative-appointments-for-equipment-relocation)

**Comment by VasilijeBursac** [comment]
[(3) g4.5: Schedule an equipment relocation appointment](https://trello.com/c/29Mz2J2m/56-3-g45-schedule-an-equipment-relocation-appointment)

**Review by kmilena98 — APPROVED** [review]
Very well.

**Review by Pufke — APPROVED** [review]

**Pull request merged**
