### PR TITLE
feat[g10]: Object info editing restriction - Only manager can edit info

### PR DESCRIPTION
**Pull request by VasilijeBursac**
Object information can be changed only by Manager. On this branch I have implemented code for editing restriction:
- User role is determined through WPF which called Graphical Editor project
- Only Manager role can see button for editing object info. Button for editing is hidden for other roles

This logic will make it very easy for us to make patient restriction (g13) later.

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(3) g9: Change basic information (name): 5h [3]](https://trello.com/c/omjRBFsz/9-3-g9-change-basic-information-name-5h-3)

**Comment by VasilijeBursac** [comment]
[(3) g10: Change additional information (description, working hours,...): 1h [1]](https://trello.com/c/VHHUGlJb/10-3-g10-change-additional-information-description-working-hours-1h-1)

**Review by milana-todorovic — APPROVED** [review]
Seems good to me, it's a pretty simple change and it looks like it does the job.

**Review by anciz — APPROVED** [review]
Nice job!

**Pull request merged**
