### PR TITLE
gui[g5.4, g5.5]: GUI for Room Schedule and Cancelling Actions

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains XAML code related to Frontend for "Show schedule for each room" and "Cancel scheduled actions":

There are few unimplemented methods related to the frontend, but they will be implemented in the next PR.

### CODE REVIEW

**Review by kmilena98 — APPROVED** [review]
Looks very good to me.

**Comment by VasilijeBursac** [comment]
[(3) g5.4: Show schedule for each room](https://trello.com/c/pbzVn3Rk/64-3-g54-show-schedule-for-each-room)

**Comment by VasilijeBursac** [comment]
[(2) g5.5: Cancel scheduled actions](https://trello.com/c/BSVF1Qrt/65-2-g55-cancel-scheduled-actions)

**Comment by VasilijeBursac** [comment]
[(3) g5.4: Show schedule for each room](https://trello.com/c/pbzVn3Rk/64-3-g54-show-schedule-for-each-room)

**Review by Pufke — APPROVED** [review]

**Review by Pufke — APPROVED** [review]

**Pull request merged**
