### PR TITLE
feat[w1.4]:adding index page for website visitor

### PR DESCRIPTION
**Pull request by sladjana-savkovic**

### CODE REVIEW

**Comment by sladjana-savkovic** [comment]
[(3) W1.2 : As a system administrator I want to observe feedbacks so that I could find out patient's opinions.](https://trello.com/c/aCBsSs6p/2-3-w12-as-a-system-administrator-i-want-to-observe-feedbacks-so-that-i-could-find-out-patients-opinions)

**Comment by sladjana-savkovic** [comment]
[(3) W1.4 : As a website user I want to observe feedbacks so that I could find out if the hospital is suitable for me.](https://trello.com/c/stvahRMG/4-3-w14-as-a-website-user-i-want-to-observe-feedbacks-so-that-i-could-find-out-if-the-hospital-is-suitable-for-me)

**Review by anciz — DISMISSED** [review]
Everything seems to be alright.

**Review by milana-todorovic — DISMISSED** [review]
Everything seems ok.

**Review by milana-todorovic — APPROVED** [review]
Seems alright.

**Review by anciz — APPROVED** [review]
Well done!

**Pull request merged**
