### PR TITLE
Feature g5.1 g5.2 tests for scheduling basic and complex renovation

### PR DESCRIPTION
**Pull request by djura023**
-Implemented tests for scheduling basic and complex renovation.

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g5.1: Schedule a basic renovation](https://trello.com/c/MO60PUeI/61-2-g51-schedule-a-basic-renovation)

**Comment by VasilijeBursac** [comment]
[(3) g5.2: Schedule a complex renovation](https://trello.com/c/egMI7Yih/62-3-g52-schedule-a-complex-renovation)

**Review by milana-todorovic — APPROVED** [review]
Seems okay, why are some tests commented out though? Did they have issues that you plan to fix later or do they need to be removed?

**Review by anciz — APPROVED** [review]

**Comment by kmilena98** [comment]
Tests will be edited soon.

**Pull request merged**
