### PR TITLE
bugfix-ia3-rabbitmq-fixes

### PR DESCRIPTION
**Pull request by borislav-puzic**
Currentli subscribe unsubscribe for actions and benefits is only applied after app restart
I want to make it posible to do that while application is running

### CODE REVIEW

**Comment by milana-todorovic** [comment]
The code for connection retrying breaks your tests for some reason, I'd just remove it for now. I think we can first figure out if we actually need this to launch with Docker Compose and then try to see what's up with the tests. Thanks for trying it out though!

**Comment by Pufke** [comment]
four tests are not performed correctly

image

**Review by milana-todorovic — APPROVED** [review]
Seems alright.

**Review by anciz — APPROVED** [review]
Alright!

**Pull request merged**
