### PR TITLE
test[w1.1, w1.3 , w3.5, w3.7]: implement end to end tests

### PR DESCRIPTION
**Pull request by draganacarapic**
* Start work on End to end test implementation

### CODE REVIEW

**Comment by draganacarapic** [comment]
[(5) W1.1 : As a patient I want to give feedback so that I could share my experience.](https://trello.com/c/k9WBa322/1-5-w11-as-a-patient-i-want-to-give-feedback-so-that-i-could-share-my-experience)

**Review by milana-todorovic — DISMISSED** [review]
Could you change the test so it uses FirefoxDriver instead of Chrome? That makes it easier to run the test in the pipeline I believe (or maybe Chrome tests can't run at all on Ubuntu agents?). @Pufke what was the exact issue with Chrome in E2E tests?

Also, since you made a new project for E2E tests, you can delete the old E2ETests projects that we used for testing purposes last sprint to avoid confustion.

**Comment by milana-todorovic** [comment]
The E2E tests haven't been added to the pipeline yet because of some technical issues we're having with Azure DevOps. A new branch will be made for fixing the pipeline.

**Review by milana-todorovic — APPROVED** [review]
The tests look good to me.

**Review by sladjana-savkovic — APPROVED** [review]

**Pull request merged**
