### PR TITLE
feat[g4.4, 4.5, 4.6]: Data entry, Scheduling Equipment Relocation and Alternative Appointments for Equipment Relocation connected with backend logic

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains "Scheduling Equipment Relocation" and "Alternative Appointments for Equipment Relocation" functionalities connected with Data Entry and Frontend

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g4.4: Entry data for equipment relocation](https://trello.com/c/VLZmjyrm/55-2-g44-entry-data-for-equipment-relocation)

**Comment by VasilijeBursac** [comment]
[(3) g4.5: Schedule an equipment relocation appointment](https://trello.com/c/29Mz2J2m/56-3-g45-schedule-an-equipment-relocation-appointment)

**Comment by VasilijeBursac** [comment]
[(5) g4.6: Alternative appointments for equipment relocation](https://trello.com/c/XUKYT4eX/57-5-g46-alternative-appointments-for-equipment-relocation)

**Review by kmilena98 — DISMISSED** [review]
Works well.

**Comment by milana-todorovic** [comment]
Build fails for me on this branch, there seem to be two classes with the same name (PatientBasicDTO) - there's only one file but it's somehow been added to the csproj twice. Also, this made me notice that the WPF build pipeline didn't actually trigger on this branch even though it should have, do you know how long this has been happening? I assume it's a build issue, do you mind if I commit a fix for that on this branch?

**Comment by VasilijeBursac** [comment]
> Build fails for me on this branch, there seem to be two classes with the same name (PatientBasicDTO) - there's only one file but it's somehow been added to the csproj twice. Also, this made me notice that the WPF build pipeline didn't actually trigger on this branch even though it should have, do you know how long this has been happening? I assume it's a build issue, do you mind if I commit a fix for that on this branch?

Feel free to commit a fix on this branch. I don't' know what happened with that class, we haven't changed that class for a  long time. Also, I haven't noticed any WPF build failures, all checks always successfully passed and the project builds well locally... I really don't have an idea what could be wrong...

**Comment by milana-todorovic** [comment]
> > Build fails for me on this branch, there seem to be two classes with the same name (PatientBasicDTO) - there's only one file but it's somehow been added to the csproj twice. Also, this made me notice that the WPF build pipeline didn't actually trigger on this branch even though it should have, do you know how long this has been happening? I assume it's a build issue, do you mind if I commit a fix for that on this branch?
> 
> Feel free to commit a fix on this branch. I don't' know what happened with that class, we haven't changed that class for a long time. Also, I haven't noticed any WPF build failures, all checks always successfully passed and the project builds well locally... I really don't have an idea what could be wrong...

I don't know, it seems to be a local issue of some sort, something happens to the csproj when I clone it. The pipeline passed when I ran it manually though, and the file seems fine on Github. 
I'll look into what's happening with the pipeline and why it's not running the build when it should, but I honestly have no idea. It runs the same check to see if which files were changed as all the other PR pipelines, but in this case it seems to fail for some reason.

**Review by milana-todorovic — DISMISSED** [review]
Seems alright.

**Comment by VasilijeBursac** [comment]
> > > Build fails for me on this branch, there seem to be two classes with the same name (PatientBasicDTO) - there's only one file but it's somehow been added to the csproj twice. Also, this made me notice that the WPF build pipeline didn't actually trigger on this branch even though it should have, do you know how long this has been happening? I assume it's a build issue, do you mind if I commit a fix for that on this branch?
> > 
> > 
> > Feel free to commit a fix on this branch. I don't' know what happened with that class, we haven't changed that class for a long time. Also, I haven't noticed any WPF build failures, all checks always successfully passed and the project builds well locally... I really don't have an idea what could be wrong...
> 
> I don't know, it seems to be a local issue of some sort, something happens to the csproj when I clone it. The pipeline passed when I ran it manually though, and the file seems fine on Github.
> I'll look into what's happening with the pipeline and why it's not running the build when it should, but I honestly have no idea. It runs the same check to see if which files were changed as all the other PR pipelines, but in this case it seems to fail for some reason.

Okay, thank you for your effort! I also don't have an idea what's the case with it, it is weird because everything seems to be fine with .csproj  locally in my case.

**Review by milana-todorovic — APPROVED** [review]

**Review by Pufke — APPROVED** [review]

**Pull request merged**
