### PR TITLE
gui[g3.1-g3.5]: Small changes in Appointment searches frontend, Back To Top button in appointment section

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains mostly small changes in XAML code for Appointment Searches Frontend. 
I implemented the Back To Top Button in the Appointment Search section.

- I left a few unimplemented methods in MainWindow.cs, but that will be replaced with implemented methods in the next commits. I did that just to avoid deleting event handler declarations from the XAML code.

- I needed to copy to App.xaml files of other WPF applications so that Application doesn't break, but in future I plan to make other WPF Apps use GraphicalEditor App.xaml without repeating code for GraphicalEditor Styles

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(5) g3.1: Search for available appointment [3]](https://trello.com/c/mY5GwcfY/41-5-g31-search-for-available-appointment-3)

**Comment by VasilijeBursac** [comment]
[(3) g3.2: Alternative appointments (priority - doctor) [2]](https://trello.com/c/nQ7uB9UY/42-3-g32-alternative-appointments-priority-doctor-2)

**Comment by VasilijeBursac** [comment]
[(3) g3.3: Alternative appointments (priority - time) [2]](https://trello.com/c/Af6vGIpt/43-3-g33-alternative-appointments-priority-time-2)

**Comment by VasilijeBursac** [comment]
[(2) g3.4: Search for available specialist appointment [2]](https://trello.com/c/cJQkTT9B/44-2-g34-search-for-available-specialist-appointment-2)

**Comment by VasilijeBursac** [comment]
[(2) g3.5: Advanced search for available appointment [1]](https://trello.com/c/aH2hW9ud/45-2-g35-advanced-search-for-available-appointment-1)

**Comment by VasilijeBursac** [comment]
[(2) g3.6: Make an appointment with a doctor [2]](https://trello.com/c/XLsPCNOm/46-2-g36-make-an-appointment-with-a-doctor-2)

**Review by vlaksi — APPROVED** [review]

**Review by anciz — APPROVED** [review]
This is good!

**Pull request merged**
