### PR TITLE
refactor[all]: edit frontend

### PR DESCRIPTION
**Pull request by draganacarapic**

### CODE REVIEW

**Review by milana-todorovic — DISMISSED** [review]
Seems alright, although I'd maybe mark things like this with style instead of refactor in the future.

**Review by anciz — DISMISSED** [review]
Well done!

**Review by vlaksi — APPROVED** [review]
Well done Dragana, you made a good job in this sprint, keep going!

**Review by anciz — APPROVED** [review]
Looks good!

**Pull request merged**
