### PR TITLE
Feature g1 hospital in doctor wpf

### PR DESCRIPTION
**Pull request by kmilena98**

### CODE REVIEW

**Comment by kmilena98** [comment]
[(1) g1: Access hospital map from current WPFs](https://trello.com/c/s3SIyZKO/13-1-g1-access-hospital-map-from-current-wpfs)

**Comment by kmilena98** [comment]
[(1) g1: Access hospital map from current WPFs](https://trello.com/c/s3SIyZKO/13-1-g1-access-hospital-map-from-current-wpfs)

**Review by milana-todorovic — COMMENTED** [review]
The part in the DoctorFrontend seems fine, just merge develop to this branch to resolve conflicts.

**Review by milana-todorovic — APPROVED** [review]

**Review by anciz — APPROVED** [review]

**Comment by kmilena98** [comment]
merge[g1]: connecting doctor WPF with hospital map

**Pull request merged**
