### PR TITLE
gui[g5.1 g5.2 g5.3]: Scheduling renovations dialog

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains mostly XAML Frontend code for scheduling renovations. 
- I also started implementing function for finding potential rooms for merging but I need to upgrade it to work better...
- I will try to reduce the amount of code in dialog XAML in some of later PRs when I find a way to combine multiple styles....

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g5.1: Schedule a basic renovation](https://trello.com/c/MO60PUeI/61-2-g51-schedule-a-basic-renovation)

**Comment by VasilijeBursac** [comment]
[(2) g5.1: Schedule a basic renovation](https://trello.com/c/MO60PUeI/61-2-g51-schedule-a-basic-renovation)

**Comment by VasilijeBursac** [comment]
[(3) g5.2: Schedule a complex renovation](https://trello.com/c/egMI7Yih/62-3-g52-schedule-a-complex-renovation)

**Comment by VasilijeBursac** [comment]
[(3) g5.3: Enter new information after scheduling a renovation](https://trello.com/c/MBN2A72C/63-3-g53-enter-new-information-after-scheduling-a-renovation)

**Review by anciz — APPROVED** [review]

**Review by djura023 — APPROVED** [review]

**Pull request merged**
