### PR TITLE
feat[g5]: Saving map to json file and retriving from file

### PR DESCRIPTION
**Pull request by ogikuzma**
Saving map to .JSON file and retrieving the map from the same file. I added FileRepository that does the saving and retrieving. Also, minor changes were made to the Room class in order to support the JSON plugin.

### CODE REVIEW

**Review by milana-todorovic — COMMENTED** [review]
Seems alright but you have conflicts, please merge develop into this branch.

**Comment by ogikuzma** [comment]
@milana-todorovic  Yes, of course

**Review by milana-todorovic — APPROVED** [review]

**Review by anciz — APPROVED** [review]
Well done!

**Comment by VasilijeBursac** [comment]
[(3) g5: Save and retrieve map drawing from .txt file](https://trello.com/c/JIDmrwBL/31-3-g5-save-and-retrieve-map-drawing-from-txt-file)

**Pull request merged**
