### PR TITLE
refactor[W2.6]: preparing doctor classes for the base

### PR DESCRIPTION
**Pull request by jelenazeljko55**
This pull request is about refactoring back-end code about doctor and survey. 
I will add the interface and classes to the repository and service.
After that, it should merge with develop branch.

### CODE REVIEW

**Comment by vlaksi** [comment]
@jelenazeljko55 read ['Definisanje cilja PR'](https://github.com/PSW-2020-ORG4/Organization-Help) and edit PR description

image

**Comment by jelenazeljko55** [comment]
[(5) W2.6 As a patient I want to fill out the survey about the hospital so that I could share my experience.](https://trello.com/c/MvcNCcZS/25-5-w26-as-a-patient-i-want-to-fill-out-the-survey-about-the-hospital-so-that-i-could-share-my-experience)

**Review by sladjana-savkovic — DISMISSED** [review]

**Review by milana-todorovic — CHANGES_REQUESTED** [review]
Seems generally alright but build fails on the Backend (I think the SurveyRepository and TherapyRepository classes weren't properly deleted for some reason so it's still looking for them? Could be an issue from deleting them on different branches and then merging the csproj file), could you fix that? Ignore any build issues in the DoctorFrontend, SecretaryFrontend, and ManagerFrontend, but the rest of the solution needs to build correctly.

**Review by sladjana-savkovic — DISMISSED** [review]

**Review by milana-todorovic — DISMISSED** [review]
Looks good to me! One note though, was your requirement for surveys that a patient can respond to the survey once per finished examination? If so, some connection between examination and survey will probably be needed eventually, but I think implementing that once you actually start working on the logic for leaving a survey and figure out exactly what you need is fine.

**Review by sladjana-savkovic — APPROVED** [review]

**Review by sladjana-savkovic — DISMISSED** [review]
Resolve conflict.

**Review by sladjana-savkovic — APPROVED** [review]

**Review by milana-todorovic — APPROVED** [review]

**Pull request merged**
