### PR TITLE
gui[g4.1]: Entry data for emergency examinations, started implementing validations

### PR DESCRIPTION
**Pull request by VasilijeBursac**
- This branch contains mostly frontend XAML code for emergency examination data entry
- On this branch I have started implementing validations, too (currently only for a patient account creation dialog)

### CODE REVIEW

**Comment by VasilijeBursac** [comment]
[(2) g4.1: Entry data for emergency examination](https://trello.com/c/VIGf5xVH/52-2-g41-entry-data-for-emergency-examination)

**Review by milana-todorovic — APPROVED** [review]
Looks nice, although it's a tiny bit annoying that the window for adding a patient shows errors as soon as it's opened before any interaction. (As far as I remember that might've been tricky to fix though, so it might not be worth the effort.)

**Comment by VasilijeBursac** [comment]
> Looks nice, although it's a tiny bit annoying that the window for adding a patient shows errors as soon as it's opened before any interaction. (As far as I remember that might've been tricky to fix though, so it might not be worth the effort.)

I absolutely agree about that... Yes, it isn't the best looking thing, I searched on how to fix that, but I could not find the most suitable solution in our case and also I didn't want to waste too much time on that. I have asked the assistant about that and she said that it is completely fine in her opinion, especially because that is not the focus of this project.

**Review by kmilena98 — APPROVED** [review]
Looks good to me.

**Pull request merged**
