### PR TITLE
Feature g5.1,g5.2 schedule basic and complex renovation

### PR DESCRIPTION
**Pull request by kmilena98**
This branch is for scheduling basic and complex renovation. If renovation can be scheduled in the chosen period, the renovation will be automatically saved, if not, the server will return the alternative appointment list. Tests will be added soon.

### CODE REVIEW

**Comment by kmilena98** [comment]
[(2) g5.1: Schedule a basic renovation](https://trello.com/c/MO60PUeI/61-2-g51-schedule-a-basic-renovation)

**Comment by kmilena98** [comment]
[(3) g5.2: Schedule a complex renovation](https://trello.com/c/egMI7Yih/62-3-g52-schedule-a-complex-renovation)

**Review by vlaksi — APPROVED** [review]
Lgtm

**Review by djura023 — APPROVED** [review]

**Comment by kmilena98** [comment]
Scheduling basic and complex renovation

**Pull request merged**
