### PR TITLE
feat[ia6.1]: tendering

### PR DESCRIPTION
**Pull request by Stefan-Kitanovic**
- Fully implemented features to create, view and accept tenders.
- Pharmacies send offers using RabbitMQ and we reply to them if we accepted or declined their offer.

### CODE REVIEW

**Comment by Stefan-Kitanovic** [comment]
[(5) IA6.1 - I as a director want to publish a tender in order to buy needed medication for the hospital.](https://trello.com/c/dHR6KTTe/20-5-ia61-i-as-a-director-want-to-publish-a-tender-in-order-to-buy-needed-medication-for-the-hospital)

**Comment by Stefan-Kitanovic** [comment]
[(5) IA6.2 - I as a pharmacist want to be able to create a tender offer for the hospital in order to win the tender](https://trello.com/c/sr3m08uN/21-5-ia62-i-as-a-pharmacist-want-to-be-able-to-create-a-tender-offer-for-the-hospital-in-order-to-win-the-tender)

**Comment by Stefan-Kitanovic** [comment]
[(1) IA6.4 - I as a director want to be able to automatically notify tender participants of their offer's outcome in order to get medications.](https://trello.com/c/TWzflXG3/27-1-ia64-i-as-a-director-want-to-be-able-to-automatically-notify-tender-participants-of-their-offers-outcome-in-order-to-get-medic)

**Review by anciz — APPROVED** [review]
Seems to be right.

**Review by milana-todorovic — APPROVED** [review]
Seems alright, although I don't really like how there's really no separation between the domain logic of tendering and the very technical details related to RabbitMQ. It definitely is pretty hard to separate in this case though, since the logic is very dependent on messaging, but I feel like there should be some sort of abstraction in place there.

**Comment by Stefan-Kitanovic** [comment]
I agree that there should be abstraction, but we weren't really sure how to do it better at this time. Perhaps it will improve when we start refactoring the project for DDD.

**Pull request merged**
